import Link from "next/link";
import ProjectShareActions from "@/components/ProjectShareActions";

export default function WazuhDetectionEngineeringPage() {
  const url = "https://www.ihowlett.com/projects/wazuh-detection-engineering";

  return (
    <main className="mx-auto max-w-5xl px-6 py-20">
      <Link
        href="/projects"
        className="text-sm font-semibold text-cyan-400 hover:text-cyan-300"
      >
        ← Back to Projects
      </Link>

      <section className="mt-8">
        <p className="text-sm font-semibold uppercase tracking-widest text-cyan-400">
          Case Study — Detection Engineering
        </p>

        <h1 className="mt-4 text-4xl font-bold md:text-5xl">
          Custom Detection Engineering and Incident Analysis Using Wazuh SIEM
        </h1>

        <p className="mt-6 text-lg leading-8 text-slate-300">
          This project focused on creating and validating a custom Wazuh
          detection rule for SSH brute-force activity. The goal was not just to
          trigger an alert, but to understand how attack behavior appears in
          logs, how detection logic works, and how alerts can support incident
          analysis.
        </p>
      </section>

      <ProjectShareActions title="Wazuh Detection Engineering Case Study" url={url} />

      <section className="mt-14"><h2 className="text-3xl font-bold">Context and Objective</h2><div className="mt-6 space-y-6 leading-8 text-slate-300"><p>Brute-force attacks are a common way attackers attempt to gain unauthorized access to systems. In this project, I simulated that behavior in a controlled lab environment using Kali Linux and Hydra against a Linux server running SSH.</p><p>The objective was to move beyond basic log collection and create a custom detection rule that could identify repeated authentication failures from a single source. This helped show how multiple lower level events can be correlated into a higher confidence security alert.</p><p>The project was completed in a VirtualBox lab using Wazuh, Kali Linux, Hydra, and a Linux target server. The final result was a working detection that generated high-severity Level 12 alerts for repeated SSH authentication failures.</p></div></section>
      <section className="mt-14"><h2 className="text-3xl font-bold">Attack Simulation</h2><div className="mt-6 space-y-6 leading-8 text-slate-300"><p>To generate realistic activity, I used Hydra from the Kali Linux machine to perform repeated SSH login attempts against the Linux server. This created authentication failures that appeared in the Linux logs and were forwarded into Wazuh.</p><p>The attack was intentionally performed in a controlled internal lab environment. The purpose was not offensive activity for its own sake, but to understand what brute-force behavior looks like from the defender’s side.</p><p>This helped connect the full chain: attacker activity, system logs, SIEM ingestion, rule processing, alert generation, and incident analysis.</p></div></section>
      <section className="mt-14 rounded-3xl border border-slate-800 bg-slate-900/70 p-8"><h2 className="text-3xl font-bold">Detection Logic</h2><div className="mt-6 space-y-6 leading-8 text-slate-300"><p>Wazuh already detected individual authentication failures, but the goal was to create a stronger rule that identified repeated failures as a pattern. This is important because one failed login attempt may not be meaningful, but many failures from the same source can indicate brute-force behavior.</p><p>The custom rule was designed to correlate multiple failed authentication events within a defined timeframe. When the pattern matched, Wazuh elevated the activity into a higher severity alert.</p><p>This showed how detection engineering turns raw event data into a more useful security signal. Instead of only seeing separate log entries, the SIEM could identify behavior that required attention.</p></div></section>
      <section className="mt-14"><h2 className="text-3xl font-bold">Troubleshooting and Refinement</h2><div className="mt-6 space-y-6 leading-8 text-slate-300"><p>The detection rule did not work correctly on the first attempt. That became one of the most valuable parts of the project because it forced me to troubleshoot the rule structure, syntax, and matching behavior.</p><p>I ran into issues with incorrect rule syntax, including the wrong use of matching conditions and configuration problems involving frequency and timeframe logic. At one point, Wazuh failed to restart because of rule file errors, which required reviewing logs and correcting the configuration.</p><p>I also learned that the original detection logic was too narrow because SSH authentication failures could be associated with multiple rule IDs. The rule had to be refined so it could better capture the relevant events.</p><p>This troubleshooting process made the project stronger. It showed that detection work is not just writing a rule once. It requires testing, validation, debugging, and refinement until the detection behaves the way it should.</p></div></section>
      <section className="mt-14"><h2 className="text-3xl font-bold">Validation and Results</h2><div className="mt-6 space-y-6 leading-8 text-slate-300"><p>After correcting the rule configuration, I ran the attack simulation again and confirmed that Wazuh successfully triggered the custom detection. The alert reached Level 12 severity and included useful investigation context such as the source IP, target system, and affected user account.</p><p>This validation step was important because it proved the detection was not just theoretical. The rule was tested against real lab activity and produced alerts that matched the intended behavior.</p><p>The final result demonstrated the value of custom detection logic: default rules provide baseline visibility, but custom rules can improve detection quality by identifying behavior patterns that matter in a real investigation.</p></div></section>
      <section className="mt-14"><h2 className="text-3xl font-bold">Skills and Concepts Demonstrated</h2><p className="mt-6 leading-8 text-slate-300">This project demonstrates hands-on detection engineering, SIEM troubleshooting, attack simulation, log analysis, validation, and incident thinking. It also connects directly to MITRE ATT&CK technique T1110 for brute-force activity.</p><div className="mt-6 flex flex-wrap gap-3">{["Wazuh SIEM","Detection Engineering","Custom Rules","SSH Brute Force","Hydra","Kali Linux","Linux Auth Logs","Alert Validation","MITRE T1110","Incident Analysis","Troubleshooting","Evidence Collection"].map((skill) => (<span key={skill} className="rounded-full border border-slate-700 bg-slate-900 px-4 py-2 text-sm text-slate-300">{skill}</span>))}</div></section>
      <section className="mt-14 rounded-3xl border border-cyan-400/30 bg-cyan-400/10 p-8"><h2 className="text-3xl font-bold">Why This Project Matters</h2><div className="mt-6 space-y-6 leading-8 text-slate-300"><p>This project matters because it shows practical detection work from start to finish. I did not only rely on default alerts — I created custom logic, tested it, broke it, fixed it, and validated the final result.</p><p>It also shows how security work often happens in real life. Detection is not always clean on the first attempt. Rules need to be tested, logs need to be understood, and configuration errors need to be solved carefully.</p><p>For me, this project was a strong step toward thinking like a SOC analyst or detection engineer: understand the behavior, identify the evidence, build a detection, validate it, and explain what happened.</p></div></section>
      <ProjectShareActions title="Wazuh Detection Engineering Case Study" url={url} />
      <section className="mt-14 rounded-3xl border border-slate-800 bg-slate-900/70 p-8"><h2 className="text-3xl font-bold">Future Improvements</h2><div className="mt-6 space-y-6 leading-8 text-slate-300"><p>One improvement would be expanding the detection logic to include additional SSH-related rule IDs and authentication patterns. This would make the detection more flexible and reduce the chance of missing related brute-force behavior.</p><p>Another improvement would be adding automated response actions, such as temporarily blocking the source IP or triggering an alert workflow for review. I would also like to expand the project with more MITRE ATT&CK mapping and additional endpoint monitoring.</p><p>Future versions could also include more attack scenarios so the same lab can support broader detection engineering practice beyond SSH brute force.</p></div></section>
      <section className="mt-14 rounded-3xl border border-slate-800 bg-slate-900/70 p-8"><h2 className="text-3xl font-bold">Full Report and Supporting Documentation</h2><p className="mt-4 leading-7 text-slate-300">The full report includes the objective, scenario, lab environment, Hydra attack simulation, Wazuh detection logic, troubleshooting notes, validation screenshots, MITRE mapping, and evidence collected during the project.</p><div className="mt-6 flex flex-wrap gap-4"><a href="/docs/wazuh-detection-engineering.pdf" target="_blank" rel="noopener noreferrer" className="rounded-xl bg-cyan-400 px-5 py-3 font-semibold text-slate-950 hover:bg-cyan-300">View Report</a><a href="/docs/wazuh-detection-engineering.pdf" download className="rounded-xl border border-slate-700 px-5 py-3 font-semibold text-slate-200 hover:border-cyan-400 hover:text-cyan-400">Download PDF</a></div><div className="mt-8 overflow-hidden rounded-2xl border border-slate-800 bg-slate-950"><iframe src="/docs/wazuh-detection-engineering.pdf" className="h-[700px] w-full bg-white" title="Wazuh Detection Engineering Report PDF" /></div></section>
    </main>
  );
}